View
yegonkimutai/Blog-app pull request #6
Opened 2023-07-18 18:51 UTC by yegonkimutai

In this PR, I did the following ;
- [ ] Create the view files for the various classes and displayed them in the UI
- [ ] Style the UI to match the wire frame design provided

2023-07-18 19:59 UTC, Ismailco requested changes
### Hi @yegonkimutai, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ UI follows the wireframes
✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 19:59 UTC, Ismailco commented on app/views/users/show.html.erb
> +<%= render @user.posts.limit(3) %>
- [ ] Nice work however you should use the `display_posts` you created in the user model to render the last 3 posts, kindly consider implementing this instead of using `@user.posts.limit(3)` to avoid repeating your self, also it's good practice to handle the app logic in the models instead of the views

2023-07-18 19:59 UTC, Ismailco commented on app/views/posts/index.html.erb
> +        <% post.comments.limit(5).each do |comment| %>
- [ ] Same here kindly consider using the `display_comments` method to render the last 5 comments in this view

2023-07-19 05:47 UTC, mikethreels approved these changes
Hi Yegon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job following the instructions of the previous CR.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 07:03 UTC, merged